#Spring Datasource Settings
spring:
  datasource:
    druid:
      name: druidDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.179.128:3308/information_schema?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123
      filters: stat
      max-active: 100
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.architecture.entity
  devtools:
    restart:
      enabled: true
      #\u8BBE\u7F6E\u91CD\u542F\u7684\u76EE\u5F55
      exclude: WEB-INF/**
      additional-paths: src/main/java

